name: flutter_project
description: "Kalinga DNWG mobile app."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Supabase
  supabase_flutter: ^2.8.0

  # HTTP package
  http: ^1.2.2

  # Environment Variables
  flutter_dotenv: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - .env
    - lib/Assets/kalinga.png
    - lib/Assets/kalinga_text.png
    - lib/Assets/account_circle.png
    - lib/Assets/chat_bubble.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/Assets/kalinga.png"